// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB538K95rm5gVLWY_65NZx5gjqrjD9EeJ0',
    appId: '1:679422611460:web:1428a9a3fc474fe7d86551',
    messagingSenderId: '679422611460',
    projectId: 'code-crafters-app',
    authDomain: 'code-crafters-app.firebaseapp.com',
    storageBucket: 'code-crafters-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdpeIZkWpnekU3dE97iRhEHdNZ0A7PCI',
    appId: '1:679422611460:android:288687779b38e3b3d86551',
    messagingSenderId: '679422611460',
    projectId: 'code-crafters-app',
    storageBucket: 'code-crafters-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVye82edgaNK4brAAM0tomOsKuf6UhtRI',
    appId: '1:679422611460:ios:7fd28dd32971ca07d86551',
    messagingSenderId: '679422611460',
    projectId: 'code-crafters-app',
    storageBucket: 'code-crafters-app.appspot.com',
    iosBundleId: 'com.example.codeMentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVye82edgaNK4brAAM0tomOsKuf6UhtRI',
    appId: '1:679422611460:ios:9893d231ab556003d86551',
    messagingSenderId: '679422611460',
    projectId: 'code-crafters-app',
    storageBucket: 'code-crafters-app.appspot.com',
    iosBundleId: 'com.example.codeMentor.RunnerTests',
  );
}
